package main

import (
	"net/http"

	"github.com/natefinch/lumberjack"
	"go.uber.org/zap"
	"go.uber.org/zap/zapcore"
)

var logger *zap.Logger
var sugarLogger *zap.SugaredLogger

func main() {
	InitLogger()
	defer sugarLogger.Sync()
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")
	simpleHttpGet("www.baidu.com")
	simpleHttpGet("http://www.baidu.com")
	simpleHttpGet("www.google.com")
	simpleHttpGet("http://www.google.com")
	simpleHttpGet("www.alibaba.com")
	simpleHttpGet("http://www.alibaba.com")
	simpleHttpGet("www.qq.com")
	simpleHttpGet("http://www.qq.com")

}

func InitLogger() {
	writeSyncer := getLogWriter()
	encoder := getEncoder()
	core := zapcore.NewCore(encoder, writeSyncer, zapcore.DebugLevel)
	logger := zap.New(core, zap.AddCaller())
	sugarLogger = logger.Sugar()
}

func simpleHttpGet(url string) {
	sugarLogger.Debugf("Trying to hit GET request for %s", url)
	resp, err := http.Get(url)
	if err != nil {
		sugarLogger.Errorf("Error fetching URL %s : Error = %s", url, err)
	} else {
		sugarLogger.Infof("Success! statusCode = %s for URL %s", resp.Status, url)
		resp.Body.Close()
	}
}

func getEncoder() zapcore.Encoder {
	encoderConfig := zap.NewProductionEncoderConfig()
	encoderConfig.EncodeTime = zapcore.ISO8601TimeEncoder
	encoderConfig.EncodeLevel = zapcore.CapitalLevelEncoder
	return zapcore.NewConsoleEncoder(encoderConfig)
}

func getLogWriter() zapcore.WriteSyncer {
	lumberJackLogger := &lumberjack.Logger{
		Filename:   "./test.log",
		MaxSize:    10,
		MaxBackups: 5,
		MaxAge:     30,
		Compress:   false,
	}
	return zapcore.AddSync(lumberJackLogger)
}
